/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_system_everydayvideo_AKey */

#ifndef _Included_com_system_everydayvideo_AKey
#define _Included_com_system_everydayvideo_AKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_system_everydayvideo_AKey
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_system_everydayvideo_AKey_getString
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_system_everydayvideo_AKey_getString1
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_system_everydayvideo_AKey_getString2
    (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_system_everydayvideo_AKey_getString3
      (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
